# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.3 on 2026-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.JSONField()),
                ("is_public", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, default="", max_length=256)),
            ],
            options={
                "verbose_name_plural": "config entries",
                "db_table": "munin_config_entry",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("app_label", models.CharField(max_length=128, unique=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("version", models.CharField(blank=True, default="", max_length=32)),
                ("has_models", models.BooleanField(default=False)),
                ("has_api", models.BooleanField(default=False)),
                ("has_admin_api", models.BooleanField(default=False)),
                ("has_admin", models.BooleanField(default=False)),
                ("has_management_commands", models.BooleanField(default=False)),
                ("has_urls", models.BooleanField(default=False)),
                ("has_channels", models.BooleanField(default=False)),
                ("has_translations", models.BooleanField(default=False)),
                ("has_fixtures", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("enabled_in_cms", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "munin_module",
                "ordering": ["display_order", "key"],
            },
        ),
    ]
